#!/usr/bin/env bash

export CONTECO_LABEL="package.ingest - ModEco"
export CONTECO_DESCRIPTION="The ModEco ingest module package based on filebeat with sasl output."

export CONTECO_TYPE="package"
export CONTECO_NAME="ingest_file_sasl"
export CONTECO_TAG="7.8.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
