#!/usr/bin/env bash


prefix="package_ingest_file_sasl_$2"


executionplane --silent docker container prune --force

if [[ "package_ingest_file_sasl_ingest_file_sasl_filebeat_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "package_ingest_file_sasl_ingest_file_sasl_filebeat_data_volume"
			result=$(docker volume ls | grep "package_ingest_file_sasl_ingest_file_sasl_filebeat_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "package_ingest_file_sasl_ingest_file_sasl_filebeat_ingest_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "package_ingest_file_sasl_ingest_file_sasl_filebeat_ingest_volume"
			result=$(docker volume ls | grep "package_ingest_file_sasl_ingest_file_sasl_filebeat_ingest_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
