#!/usr/bin/env bash


prefix="package_ingest_file_sasl_$2"

if [[ "package_ingest_file_sasl_ingest_file_sasl_filebeat_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_file_sasl_ingest_file_sasl_filebeat_data_volume
	fi
	
if [[ "package_ingest_file_sasl_ingest_file_sasl_filebeat_ingest_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_file_sasl_ingest_file_sasl_filebeat_ingest_volume
	fi
	
if [[ "package_ingest_file_sasl_ingest_file_sasl_filebeat_ingest_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v package_ingest_file_sasl_ingest_file_sasl_filebeat_ingest_volume:/conteco/pwd ${CONTECO_REGISTRY}$1 --interactive cp -r /modeco/volumes/ingest_file_sasl_filebeat_ingest_volume/* /conteco/pwd
		fi
		
